<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Trureturing.Intuition.StructureCounterfactual</RootNamespace>
    <AssemblyName>Trureturing.Intuition.StructureCounterfactual</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Trureturing.Intuition.Core/Trureturing.Intuition.Core.csproj" />
  </ItemGroup>
</Project>
